FROM tensorflow/tensorflow:latest-gpu-py3

RUN apt-get update && apt-get install -y --no-install-recommends \
        iproute2 \
        git \
        pandoc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install fire toolz scikit-learn
RUN git clone https://github.com/msalvaris/gpu_monitor.git && \
	pip install -r gpu_monitor/requirements.txt && \
	pip install -e gpu_monitor


