FROM nvidia/cuda:7.5-cudnn5-devel

RUN apt-get update && apt-get install -y --no-install-recommends \
         build-essential \
         cmake \
         git \
         curl \
         vim \
         ca-certificates \
         libjpeg-dev \
         libpng-dev &&\
     rm -rf /var/lib/apt/lists/*

RUN curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-4.2.12-Linux-x86_64.sh  && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \
     rm ~/miniconda.sh && \
     /opt/conda/bin/conda install conda-build && \
     /opt/conda/bin/conda create -y --name py35 python=3.5.2 numpy pyyaml scipy ipython mkl scikit-learn jupyter&& \
     /opt/conda/bin/conda clean -ya
ENV PATH /opt/conda/envs/py35/bin:$PATH

COPY ssh_config /root/.ssh/config
RUN apt-get update && apt-get install -y --no-install-recommends \
        iproute2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


RUN bash -c "source activate py35 && \
			 pip install fire toolz scikit-learn cupy==2.0.0rc1 chainer==3.0.0rc1 papermill && \
			 git clone https://github.com/msalvaris/gpu_monitor.git && \
			 pip install -r gpu_monitor/requirements.txt && \
			 pip install -e gpu_monitor"


