FROM mxnet/python:gpu

RUN rm /usr/bin/python &&\
	ln -s /usr/bin/python3 /usr/bin/python &&\
	rm /usr/local/bin/pip &&\
	ln -s /usr/local/bin/pip3 /usr/bin/pip

COPY ssh_config /root/.ssh/config
RUN apt-get update && apt-get install -y --no-install-recommends \
        openssh-client \
        openssh-server \
        iproute2 \
        pandoc \
        git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    # configure ssh server and keys
    && mkdir /var/run/sshd \
    && ssh-keygen -A \
    && sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config \
    && sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd \
    && ssh-keygen -f /root/.ssh/id_rsa -t rsa -N '' \
    && chmod 600 /root/.ssh/config \
    && chmod 700 /root/.ssh \
    && cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys


RUN pip3 install fire toolz jupyter scipy scikit-learn ipykernel

RUN git clone https://github.com/msalvaris/gpu_monitor.git && \
	pip3 install -r gpu_monitor/requirements.txt && \
	pip3 install -e gpu_monitor

EXPOSE 23
CMD ["/usr/sbin/sshd", "-D", "-p", "23"]

