FROM mxnet/python:gpu

RUN rm /usr/bin/python &&\
	ln -s /usr/bin/python3 /usr/bin/python &&\
	rm /usr/local/bin/pip &&\
	ln -s /usr/local/bin/pip3 /usr/bin/pip

RUN apt-get update && apt-get install -y --no-install-recommends \
        iproute2 \
        pandoc \
        git \
        locales \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN pip3 install fire toolz jupyter scipy scikit-learn ipykernel papermill 

RUN git clone https://github.com/msalvaris/gpu_monitor.git && \
	pip3 install -r gpu_monitor/requirements.txt && \
	pip3 install -e gpu_monitor



