FROM tensorflow/tensorflow:latest-gpu-py3

#COPY ssh_config /root/.ssh/config
RUN apt-get update && apt-get install -y --no-install-recommends \
#        openssh-client \
#        openssh-server \
        iproute2 \
        git \
        pandoc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    # configure ssh server and keys
#    && mkdir /var/run/sshd \
#    && ssh-keygen -A \
#    && sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config \
#    && sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd \
#    && ssh-keygen -f /root/.ssh/id_rsa -t rsa -N '' \
#    && chmod 600 /root/.ssh/config \
#    && chmod 700 /root/.ssh \
#    && cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys

RUN pip install fire toolz scikit-learn
RUN git clone https://github.com/msalvaris/gpu_monitor.git && \
	pip install -r gpu_monitor/requirements.txt && \
	pip install -e gpu_monitor

#EXPOSE 23
#CMD ["/usr/sbin/sshd", "-D", "-p", "23"]

