FROM microsoft/cntk:2.1-gpu-python3.5-cuda8.0-cudnn6.0

RUN apt-get update && apt-get install -y --no-install-recommends \
        iproute2 \
        git \
        locales \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN git clone https://github.com/msalvaris/gpu_monitor.git

RUN bash -c "source /cntk/activate-cntk && \
			 pip install fire toolz==0.8.2 scikit-learn bokeh==0.12.6 pandas==0.19.1 pypandoc==1.4 influxdb==5.0.0 papermill &&\
			 pip install --upgrade requests"


RUN bash -c "source /cntk/activate-cntk && \
			 pip install -r gpu_monitor/requirements.txt && \
			 pip install --no-deps -e gpu_monitor"


